Product cards n
ruudyaa/codebusters pull request #24
Opened 2023-01-16 09:12 UTC by smiadv2022

скрипти підключено технічно поки не узгоджено загальний варіант

2023-01-16 14:18 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +              <input class="product__mdform-input" id="name" type="text" name="product-form-name" id="name"
приберіть лишній id="name"

2023-01-16 14:24 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +      <h4 class="product__md-title">Chololate icecream</h4>
це <h2>

2023-01-16 14:26 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +      <div class="product__modal-tumbimg"></div>
tumbimg - thumbimg. Немає слова "tumb"

2023-01-16 14:32 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +          <li class="product_benefit-item">
product__benefit-item - загубили нижній прочерк.

2023-01-16 14:33 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +              <div class="product__benefit-tumb">
products-benefits__thumb

2023-01-16 14:33 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +                  <p class="product__benefit-value">320</p>
products-benefits__value

2023-01-16 14:33 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +              <p class="product__benefit-descr">kcal</p>
products-benefits__description

2023-01-16 14:34 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +              <div class="product__benefit-tumb">
products-benefits__thumb

2023-01-16 14:34 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +                  <p class="product__benefit-value">4g</p>
products-benefits__value

2023-01-16 14:34 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +              <p class="product__benefit-descr">Prote<span class="product__benefit-hidden">in</span>...</p>
products-benefits__description

2023-01-16 14:34 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +          <li class="product_benefit-item">
products-benefits__item

2023-01-16 14:35 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +              <div class="product__benefit-tumb">
product__benefit-thumb - не tumb

2023-01-16 14:35 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +                  <p class="product__benefit-value">8,2g</p>
products-benefits__value

2023-01-16 14:35 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +              <p class="product__benefit-descr">Fats</p>
products-benefits__description

2023-01-16 14:35 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +          <li class="product_benefit-item">
products-benefits__item

2023-01-16 14:36 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +              <div class="product__benefit-tumb">
products-benefits__thumb

2023-01-16 14:36 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +                  <p class="product__benefit-value">40,4g</p>
products-benefits__value

2023-01-16 14:36 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +              <p class="product__benefit-descr">Carbs</p>
products-benefits__description

2023-01-16 14:36 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +      <div class="product__md-ingred">
products-ingredients

2023-01-16 14:37 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +          <h4 class="product__ingred-title">Ingredients</h4>
<h2>
products-ingredients__title

2023-01-16 14:37 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +          <div class="product__md-ingred-tabl">
products-ingredients__table

2023-01-16 14:37 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +              <ul class="product__ingred-descr">
products-ingredients__description

2023-01-16 14:38 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +                  <li class="product__ingred-item">Milk</li>
products-ingredients__item

2023-01-16 14:38 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +                  <li class="product__ingred-item">Cream</li>
products-ingredients__item

2023-01-16 14:38 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +                  <li class="product__ingred-item">Cocoa powder</li>
products-ingredients__item

2023-01-16 14:38 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +                  <li class="product__ingred-item">Vanilla sugar</li>
products-ingredients__item

2023-01-16 14:39 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +              <ul class="product__ingred-value">
products-ingredients__value-list

2023-01-16 14:40 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +                  <li class="product__ingred-item">100ml</li>
products-ingredients__value

2023-01-16 14:40 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +                  <li class="product__ingred-item">20g</li>
products-ingredients__value

2023-01-16 14:40 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +                  <li class="product__ingred-item">150 ml</li>
products-ingredients__value

2023-01-16 14:40 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +                  <li class="product__ingred-item">40g</li>
products-ingredients__value

2023-01-16 14:40 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +                  <li class="product__ingred-item">10g</li>
products-ingredients__value

2023-01-16 14:43 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +                  placeholder=" ">
Немає плейсхолдера

2023-01-16 14:45 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +                  name="product-form-phone" required autocomplete="off" placeholder=" ">
немає плейсхолдера

2023-01-16 14:55 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +  display: block;
непотрібно

2023-01-16 14:55 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +  flex-direction: column;
непотрібно.

2023-01-16 14:58 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +  align-items: center;
потрібно додати: 
  width: 100%;
  height: 100%;
  
align-items: center; - прибрати

2023-01-16 14:58 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +  background-color:  rgba(0, 0, 0, 0.7);;
background-color: rgba(0, 0, 0, 0.2);

2023-01-16 14:59 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +  bottom: 0;
прибрати:
bottom: 0;
right: 0;

2023-01-16 15:00 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +  overflow-y: auto;
прибрати:
  overflow-y: auto;
  scale:1;

2023-01-16 15:01 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    scale:0.5;
scale:0.5; - прибрати
visibility: hidden; - додати

2023-01-16 15:05 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    opacity: 0;
цей код приберіть. Тут має бути трансформація
    opacity: 0; 
    pointer-events: none;
    scale:0.1;
    top:0;
    left:0;

2023-01-16 15:08 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    height: auto;
height: 968px

2023-01-16 15:08 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    border: 2px solid #F8D24E;
колір в змінній має бути

2023-01-16 15:10 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    display: flex;
приберіть :
    display: flex;
    flex-direction: column;
    align-items: center;

2023-01-16 15:11 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    overflow:hidden;
прибрати:

    overflow:hidden;
    overflow-y: auto;
    scale:1;

2023-01-16 15:12 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    transform: translate(-50%, -50%) ;
тут на місці transform: transform 250ms cubic-bezier(0.4, 0, 0.2, 1);

2023-01-16 15:12 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +
додати:

  .is-hidden-product & {
    transform: translate(-50%, -50%) scale(0);
  }

2023-01-16 15:15 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
@include desktop {
.product__modal {
width: 568px;
height: 996px;
padding: 32px 40px;
}

2023-01-16 15:31 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +
потрібно задати розмір модалки для мобільного через медіа-запит
  
  @media screen and (max-width: 767px) {
    width: 280px;
    height: 968px
  }

2023-01-16 15:37 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +
додати:
  display: flex;
  justify-content: center;
  align-items: center;

2023-01-16 15:38 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +
додати: 
  color: getColor('theme-black');
  cursor: pointer;
  
   transition: color 250ms cubic-bezier(0.4, 0, 0.2, 1);

2023-01-16 15:39 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
прибрати цей медіазапит

2023-01-16 15:41 UTC, ruudyaa commented on src/partials/modals/products-card.html
> +      <div class="product__md-close">
прибрати цей дів, він не потрібен

2023-01-16 15:42 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +.product__md-close{
прибрати ці стилі для діву

2023-01-16 15:43 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +}
додати цей код для кнопки:
position:absolute;
top:12px;
right:12px;
display: flex;
justify-content: center;
align-items: center;
color: getColor('theme-black');
cursor: pointer;

transition: color 250ms cubic-bezier(0.4, 0, 0.2, 1);

2023-01-16 15:44 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +}
додати хувер та фокус для кнопки:
  &:hover,
  &:focus {
    color: getColor('orange-main');
  }

2023-01-16 15:47 UTC, smiadv2022 commented on src/partials/modals/products-card.html
> +      <h4 class="product__md-title">Chololate icecream</h4>
Прошу уточнити - що пропонується змінитии в тегах

2023-01-16 15:47 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    display:block;
прибрати весь код та замість додати цей:
    fill: currentColor;
    width: 11px;
    height: 11px;

2023-01-16 15:47 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
прибрати цей код та замість нього:
  @include tablet {
    width: 24px;
    height: 24px;
}

2023-01-16 15:50 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    font-size: 20px;
спочаткум додаємо стилі для мобільного:
 font-family: 'Seymour One';
 text-align: center;
 font-size: 16px;
  line-height: calc(24 / 16);
  text-align: center;
  color: getColor('theme-black');
  letter-spacing: 0;
  width: 221px;
  height: 72px;
  margin: 0 auto 20px;

2023-01-16 15:51 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +
потім для планшета та декстопу:
  @include tablet {
    font-size: 20px;
    line-height: calc(28 / 20);
    width: 322px;
    height: 84px;
    margin: 0 auto 24px;
  }

2023-01-16 15:51 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
це прибрати
@media screen and (min-width: 1200px) {
    .product__md-title{
        margin-bottom: 31px;
    }
}

2023-01-16 16:11 UTC, smiadv2022 commented on src/partials/modals/products-card.html
> +              <input class="product__mdform-input" id="name" type="text" name="product-form-name" id="name"
ok

2023-01-16 16:12 UTC, smiadv2022 commented on src/partials/modals/products-card.html
> +      <div class="product__modal-tumbimg"></div>
ok

2023-01-16 16:12 UTC, smiadv2022 commented on src/partials/modals/products-card.html
> +          <li class="product_benefit-item">
ok

2023-01-16 16:12 UTC, smiadv2022 commented on src/partials/modals/products-card.html
> +              <div class="product__benefit-tumb">
ok

2023-01-16 16:12 UTC, smiadv2022 commented on src/partials/modals/products-card.html
> +              <div class="product__benefit-tumb">
ok

2023-01-16 16:15 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +  display: block;
ok

2023-01-16 16:16 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +  flex-direction: column;
ok

2023-01-16 16:21 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +  align-items: center;
ok

2023-01-16 16:21 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +  background-color:  rgba(0, 0, 0, 0.7);;
ok

2023-01-16 16:24 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +  bottom: 0;
top=0, left=0, bottom=0, right=0 -  це замість width=100%  height=100%  . Видаляю згідно коментарів

2023-01-16 16:24 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    min-width: 132px;
max-width: 132px;

2023-01-16 16:25 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    min-height: 132px;
max-height: 139px;

2023-01-16 16:26 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +  overflow-y: auto;
Якщо убрати overflow-y: auto, то на мобільниках з невеликою висотою вже немає доступу до кнопок внизу, наприклад. Але видаляю згідно коментів.

2023-01-16 16:26 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
@include tablet {
margin-bottom: 24px;
}

2023-01-16 16:27 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
@media screen and (min-width: 1200px) - цей запит потрібно прибрати

2023-01-16 16:27 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    ion: all 300ms linear;
приберіть поки анімацію, на додаток, вона написана з помилкою

2023-01-16 16:28 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +.product__modal-tumbimg:hover.product__modal-tumbimg:before {
це поки можна прибрати

2023-01-16 16:32 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
@media screen and (min-width: 1200px) - прибрати
@include tablet  - додати

2023-01-16 16:37 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +.product_benefit-item:hover  {
це потрібно прибрати

2023-01-16 16:42 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    border: 2px solid #9CBE8F;
колір має бути змінною

2023-01-16 16:44 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +.product__benefit-hidden{
для якого елементу цей клас? його немає в HTML

2023-01-16 16:46 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +.product__benefit-tumb{
змінити назву класу

2023-01-16 16:49 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    opacity: 0;
Прибрала весь  клас 
b_ackdrop.is-hidden-product .product__modal {_
Яка трансформація повинна бути  не зрозуміло.

2023-01-16 16:49 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +.product__benefit-tumb{
.product__benefit-thumb

2023-01-16 16:52 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +        margin-bottom: 7px;
margin-bottom: 6px;

2023-01-16 16:52 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    border-color:#9CBE8F; ;
колір - змінна

2023-01-16 16:52 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    border-color:#9CBE8F; ;
колір - змінна

2023-01-16 16:52 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    height: auto;
width: 280px;
    height: auto; - це розміри, які повинні бути у модального вікна до десктопного розміру. На мій погляд їх прибирати неможна.  По замовчуванню - 280пикс, а з десктопа - 568пикс

2023-01-16 16:52 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    margin-bottom: 9px;
margin-bottom: 8px;

2023-01-16 16:53 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
@media screen and (min-width: 1200px) - прибрати
@include tablet { - додати
}

2023-01-16 16:54 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
https://github.com/media screen and (min-width: 1200px) - прибрати
@include tablet { - додати
}

2023-01-16 16:54 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +        font-weight: 500;
прибрати

2023-01-16 16:54 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    border: 2px solid #F8D24E;
ok

2023-01-16 16:55 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    line-height: 2.8;
видалити лишній line-height: 2.8;

2023-01-16 16:56 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    font-size: 12px;
font-size: 10px;
line-height: calc( 28 / 10);

2023-01-16 16:58 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    .product__benefit-value{
@include tablet {
font-size: 12px;
line-height: calc( 28 / 12);
}

2023-01-16 16:59 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    line-height: 1.2;
line-height: calc(12 / 10);

2023-01-16 17:02 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    display: flex;
Не згідна прибрати ці теги- це основна обгортка всього вікна і вона тримає все наповнення вікна у потрібній геометрії.

2023-01-16 17:04 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    overflow:hidden;
ок

2023-01-16 17:06 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
https://github.com/media screen and (min-width: 1200px) - прибрати
@include tablet { - додати
}

2023-01-16 17:06 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +        line-height: 1.25;
line-height: calc( 12 / 15);

2023-01-16 17:28 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    background: #9CBE8F;
колір - змінна

2023-01-16 17:28 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    border-color:#9CBE8F; ;
колір - змінна

2023-01-16 17:30 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    line-height: 1.4;
line-height: calc(28 / 20);

2023-01-16 17:31 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +.product__md-ingred-tabl:hover{
не потрібен хувер, потрібно прибрати

2023-01-16 17:31 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    line-height: 1.76;
line-height: calc( 24 / 12);

2023-01-16 17:32 UTC, smiadv2022 commented on src/partials/modals/products-card.html
> +      <div class="product__md-close">
Цей дів позіціонує кнопку. Не бачу змісту його прибирати, бо все ламається.

2023-01-16 17:34 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    line-height: 1;
line-height: calc(17 / 12);

2023-01-16 17:34 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
@media screen and (min-width: 1200px) { - прибрати
@include tablet { - додати

2023-01-16 17:35 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    }
line-height: calc( 20 / 14);

2023-01-16 17:37 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    border: 1px solid #84A178;
колір - змінна

2023-01-16 17:38 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
https://github.com/media screen and (min-width: 1200px) { - прибрати
@include tablet { - додати

2023-01-16 17:39 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    line-height: 1.40;
line-height: calc(20 / 14);

2023-01-16 17:42 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    background: #FCFCFC;
колір - змінна

2023-01-16 17:42 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    line-height: 1.40;
line-height: calc(20 / 14);

2023-01-16 17:43 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +background: #FCFCFC;
колір- змінна

2023-01-16 17:45 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +line-height: 1;
прибрати

2023-01-16 17:47 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    min-height: 84px;
max-height: 84px;

2023-01-16 17:49 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +}
@include tablet {
padding: 11px 16px;
width: 368px;

2023-01-16 17:49 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
@media screen and (min-width: 1200px) { - прибрати
@include tablet { - додати

2023-01-16 17:50 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    line-height: 1.40;
line-height: calc(20 / 14);

2023-01-16 17:50 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    background: #FCFCFC;
колір - змінна

2023-01-16 17:50 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    line-height:1;
line-height: calc(20 / 14);

2023-01-16 17:51 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +    line-height: 1.21;
line-height: calc(20 / 14);

2023-01-16 17:51 UTC, ruudyaa commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
@media screen and (min-width: 1200px) { - прибрати
@include tablet { - додати

2023-01-16 17:52 UTC, ruudyaa requested changes
Виправте вказані помилки

2023-01-16 18:10 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    font-size: 20px;
в мене однакові шрифти для десктопа і для мобілки  на title для модалки font-size: 20px;
line-height: 28px;, а не 16пикселів
маржин в мене 27пикселів, бо це зміщене на 7 пикселів коло з тінню, від якого позіціонується картинка, яка і має відступ 20 пікселів

2023-01-16 18:14 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    min-width: 132px;
ok

2023-01-16 18:15 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    min-height: 132px;
розмір 132. на 7 пикселів зміщено befor

2023-01-16 18:16 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
всі медіа запити змінила на міксини

2023-01-16 18:19 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    border: 2px solid #9CBE8F;
В змінних такого кольору немає. Не додавала, щоб не було конфліктів

2023-01-16 18:25 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    border-color:#9CBE8F; ;
Немає кольору у змінних

2023-01-16 18:34 UTC, smiadv2022 commented on src/partials/modals/products-card.html
> +                  placeholder=" ">
По макету - тільки лейбл замість плейсхолдера в інпуті.  Лейбла окремо немає

2023-01-16 18:37 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +
Не зрозуміло куди додавати, бо хіден -це технічне закриття. Як будо з JS -  поки чітко невідомо.

2023-01-16 18:38 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
ок

2023-01-16 18:38 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +
Цей розмір 280 px актуальний до десктопа. Навіщо   робити запит от 767,  якщо між 767 і 1220 немає іншого варіанту розміру? Висота вираховується автоматично, бо комент користувач може змінювати по вертикалі. Чи розмір текстаріал фіксуємо?

2023-01-16 18:38 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
ок

2023-01-16 18:41 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +.product__md-close{
ок

2023-01-16 18:42 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +}
ок

2023-01-16 18:42 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +}
ок

2023-01-16 18:44 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    display:block;
fill: currentColor  додала.   Розміри перевірила - зараз за макетом.

2023-01-16 18:45 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
розміри за макетом з урахуванням  іконки mobile_menu_x

2023-01-16 18:48 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
ok

2023-01-16 18:49 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
ok

2023-01-16 18:49 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    ion: all 300ms linear;
прибрала

2023-01-16 18:50 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
ok

2023-01-16 18:50 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +.product_benefit-item:hover  {
ok

2023-01-16 18:51 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +.product__benefit-tumb{
ok

2023-01-16 18:56 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +        margin-bottom: 7px;
ok

2023-01-16 18:56 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    border-color:#9CBE8F; ;
чекаю змінну

2023-01-16 18:56 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    margin-bottom: 9px;
ок

2023-01-16 18:57 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
ок

2023-01-16 18:57 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
ок

2023-01-16 18:57 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +        font-weight: 500;
ок

2023-01-16 18:58 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    line-height: 2.8;
ок

2023-01-16 19:01 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    font-size: 12px;
для десктопа фонт-сайз - 12пикселів,

2023-01-16 19:04 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    .product__benefit-value{
є два розміри - десктоп і не десктоп.  змінила згідно ваших коментарів на варіант :  мобілка і  від таблета і далі. .

2023-01-16 19:05 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    line-height: 1.2;
12/10 дає 1,2. Навіщо рахувати окремою функцією?. На лекціях давали рекомендації вносити конкретні дані.

2023-01-16 19:05 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
ок

2023-01-16 19:06 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +        line-height: 1.25;
якщо через калк, то 15/12. результат внесено вірно.

2023-01-16 19:09 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    background: #9CBE8F;
чекаю змінну

2023-01-16 19:09 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    border-color:#9CBE8F; ;
чекаю змінну

2023-01-16 19:09 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    line-height: 1.4;
внесено вірно

2023-01-16 19:10 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +.product__md-ingred-tabl:hover{
ок

2023-01-16 19:13 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    line-height: 1.76;
по макету - 14 пх, лайн-х - 1,76

2023-01-16 19:15 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    line-height: 1;
проставила 1,4. 
По макету font-size: 14px

2023-01-16 19:16 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
ок

2023-01-16 19:18 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    }
шрифт для інпутів однаковий для різних пристроїв

2023-01-16 19:19 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    border: 1px solid #84A178;
ок

2023-01-16 19:19 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
ок

2023-01-16 19:21 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    background: #FCFCFC;
ок

2023-01-16 19:22 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    line-height: 1.40;
за макетом - 140%, тобто 1.4.

2023-01-16 19:22 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +background: #FCFCFC;
ок

2023-01-16 19:24 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +line-height: 1;
ок

2023-01-16 19:28 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
ок

2023-01-16 19:28 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    line-height: 1.40;
л-х- по макету - 140%

2023-01-16 19:28 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    background: #FCFCFC;
ок

2023-01-16 19:29 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    line-height:1;
видалила л-х

2023-01-16 19:32 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +    line-height: 1.21;
для макету на кнопці шрифт 14, лх-17. Тобто 17/14=1,21

2023-01-16 19:33 UTC, smiadv2022 commented on src/sass/layout/modals/_products-card.scss
> +@media screen and (min-width: 1200px) {
ок

2023-01-17 10:57 UTC, ruudyaa approved these changes

2023-01-17 10:57 UTC, merged