Products dmitriy kolisnichenko
ruudyaa/codebusters pull request #28
Opened 2023-01-16 15:23 UTC by DmitriyK2512

2023-01-16 19:41 UTC, blowmybow requested changes

2023-01-16 19:41 UTC, blowmybow commented on src/partials/products.html
> +        <!-- <picture>
не потрібно залишати коміти, файл повинен бути чистим

2023-01-16 19:41 UTC, blowmybow commented on src/partials/products.html
> +        <!-- <picture>
так само щодо комітів

2023-01-16 19:41 UTC, blowmybow commented on src/partials/products.html
> +        <!-- <picture>
так само щодо комітів

2023-01-16 19:41 UTC, blowmybow commented on src/sass/index.css
> +@media screen and (min-device-pixel-ratio: 2) and (min-width: 1200px), screen and (-webkit-min-device-pixel-ratio: 2) and (min-width: 1200px), screen and (min-resolution: 192dpi) and (min-width: 1200
неправильно визначені медіа правила, картники працюють некоректно

2023-01-16 19:41 UTC, blowmybow commented on src/sass/index.css
> +@media screen and (min-device-pixel-ratio: 2) and (min-width: 767px), screen and (-webkit-min-device-pixel-ratio: 2) and (min-width: 767px), screen and (min-resolution: 192dpi) and (min-width: 767px)
неправильно визначені медіа правила, картники працюють некоректно

2023-01-16 19:41 UTC, blowmybow commented on src/sass/index.css
> +@media screen and (min-device-pixel-ratio: 2) and (max-width: 1199px), screen and (-webkit-min-device-pixel-ratio: 2) and (max-width: 1199px), screen and (min-resolution: 192dpi) and (max-width: 1199
неправильно визначені медіа правила, картники працюють некоректно

2023-01-16 19:41 UTC, blowmybow commented on src/sass/index.css
> +@media screen and (min-device-pixel-ratio: 2) and (max-width: 767px), screen and (-webkit-min-device-pixel-ratio: 2) and (max-width: 767px), screen and (min-resolution: 192dpi) and (max-width: 767px)
неправильно визначені медіа правила, картники працюють некоректно

2023-01-16 19:41 UTC, blowmybow commented on src/sass/layout/_products.scss
> +  font-family: 'Montserrat';
не потріьно

2023-01-17 00:25 UTC, ruudyaa approved these changes

2023-01-17 00:27 UTC, merged